### ISSUE TITLE
What KeePass arguments do I need to use in cmd, in order to create the PLGX file from source myself?

### ISSUE THREAD

**Issue by buzzybees** [tiuub/KeeOtp2#23]
I am extra paranoid and I tend not to use prepared PLGX files of plugins. 

I would like to know how to do the entire process myself, since I do not have experience making something as such. 

I have read some documentation on the official site and attempted this (the first KeeOtp2 directory after Downloads is the entire KeeOtp2 repository, cloned):
`KeePass.exe --plgx-create C:\Users\BuzzyBee\Downloads\KeeOtp2\KeeOtp2`

The output file turned out to be corrupt, therefore KeePass could not compile it. I assume it does not contain all required files.

Thanks in advance, help is appreciated!

**Comment by tiuub** [comment]
Hello,
just use the batch files I will post below. It might be an issue because of the dependencies I used in the project.
Put the files in the root path and run the batch file. The output plgx will be moved to a newly created Releases folder.

[makeplgx.zip](https://github.com/tiuub/KeeOtp2/files/6633292/makeplgx.zip)
