### ISSUE TITLE
Ctrl + A not working!!!

### ISSUE THREAD

**Issue by gabycmc** [tiuub/KeeOtp2#27]
I've tried every trouble shouting mentioned and the select all function (Ctrl + A) still DOES NOT WORK!!! Ctrl C, Ctrl V, Ctrl X, etc all work.  Ctrl A is the only one that does not work.  Just stopped worked suddenly.  Has anyone had this issue that can help me?  It doesn't work in anything.  Not in Word, Excel, or anything else.  I use Windows 10 Pro.  Have a Logi Ergo K860 keyboard & a HP laptop. I've downloaded every possible driver and nothing either. There are no Windows updates, BIOS updates, or anything like that needed.  HEEELLLPPP MEEEE!

**Comment by tiuub** [comment]
Hey @gabycmc,

thank you for your submission.

I'm not sure, but this plugin doesn't bind the hotkey CTRL+A. By default, the only hotkeys are CTRL+T, while selecting an entry and CTRL+ALT+T for global auto-type. So this plugin shouldn't be responsible for your issue. Did you install other software, like AutoHotKey?

I'm busy right now, but I will try giving you further advise this evening. Please stay patient.

Kind regards

**Comment by gabycmc** [comment]
@tiuub 

Couldn't figure it out either huh?

**Comment by tiuub** [comment]
As I said, this plugin does not bind the hotkey CTRL-A by default. So this issue can't happen due to this plugin.

The only thing which is possible, is that you have bind CTRL-A as global hotkey for entering the otp. Therefore please navigate to KeePass->Tools->KeeOtp2->Settings and set the hotkey sequence to anything else than CTRL-A.

If this doesn't work for you, you have to give me more details about this issue. Like, does it also happen if you completely close KeePass. At the moment, I can't reproduce your issue.

Kind regards
