### ISSUE TITLE
{TOTP} placeholder vs. {TIMEOTP} placeholder

### ISSUE THREAD

**Issue by Elenkhos** [tiuub/KeeOtp2#3]
Hi,

KeeOtp2 uses the Keepass native support for TOTP and its placeholder is {TIMEOTP}. So why KeeOtp2 has also its own placeholder {TOTP}? I think this can be a bit confusing for the user. I don't know which one is preferred to use and is there any difference between them.

Maybe you should consider using only the native {TIMEOTP} placeholder or adding explanation in the documentation about the preferred placeholder and their differences.

**Comment by tiuub** [comment]
Hi,

the {TOTP} placeholder is only for downwards compatibility, because some people still have this placeholder in their database from the original KeeOtp.

I will consider this in the next update and give a recommendation in the documentation or inside the plugin.

Thank you for submitting!

Best regards
tiuub
