### ISSUE TITLE
Is this basically an alternative for Google authenticator or Authy?

### ISSUE THREAD

**Issue by vespino** [tiuub/KeeOtp2#6]
So forgive me for maybe asking a stupid question, but is this plugin an alternative for Google authenticator or Authy? If yes: how would I go about using this on my phone?

**Comment by tiuub** [comment]
No problem. How to learn something, if you dont ask someone? 

So the simple answer is, this plugin is a alternative for both Google and Authy. This is because generating Time-Based One-Time-Passwords (TOTP) is standarized by [RFC 6238](https://tools.ietf.org/html/rfc6238). Due to this standard, it is possible to give the user the freedom to choose its favourite TOTP Generator. So you only need to know your secret, which was shown to you during the setup process of 2fa in your website (like Google, Github, etc.), so you can enter this secret in Google Authenticator or Authy or even this plugin. So its up to you, which generator you want to use.

If you want to use this plugin on Android, you can simply setup your 2fa with this plugin on your computer and then use (Keepass2Android)[https://play.google.com/store/apps/details?id=keepass2android.keepass2android&hl=de&gl=US]. It supports TOTP for KeePass Databases on Android.

**Comment by vespino** [comment]
Thanks for explaining. I'm an iPhone user, so unfortunately this won't work for me.
